// env.js
import dotenv from "dotenv";
dotenv.config();

export const ENV = {
  NODE_ENV: process.env.NODE_ENV || "development",
  PORT: process.env.PORT || 5000,
  MONGO_URI: process.env.MONGO_URI || "mongodb://localhost:27017/aiwaf",
  EMAIL_USER: process.env.EMAIL_USER || "",
  EMAIL_PASS: process.env.EMAIL_PASS || "",
  ALERT_EMAIL_RECIPIENT: process.env.ALERT_EMAIL_RECIPIENT || "",
  POLICY_PATH: process.env.POLICY_PATH || "./utils/policy.json",
  FASTAPI_URL: process.env.FASTAPI_URL || "http://localhost:8000",
  FASTAPI_TIMEOUT_MS: process.env.FASTAPI_TIMEOUT_MS || "750",
  API_KEYS: process.env.API_KEYS || "",
  DASHBOARD_TOKEN_SECRET: process.env.DASHBOARD_TOKEN_SECRET || "",
  DASHBOARD_TOKEN_TTL_SECONDS: process.env.DASHBOARD_TOKEN_TTL_SECONDS || "28800",
  ADMIN_USERNAME: process.env.ADMIN_USERNAME || "admin",
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || "",
  ADMIN_ROLE: process.env.ADMIN_ROLE || "owner",
  PROXY_TARGET: process.env.PROXY_TARGET || "",
  UPSTREAM_ALLOWLIST: process.env.UPSTREAM_ALLOWLIST || process.env.PROXY_TARGET || "",
  PROXY_REQUEST_TIMEOUT_MS: process.env.PROXY_REQUEST_TIMEOUT_MS || "5000",
  RATE_LIMIT_WINDOW_MS: process.env.RATE_LIMIT_WINDOW_MS || "60000",
  RATE_LIMIT_MAX: process.env.RATE_LIMIT_MAX || "120",
  AUTH_RATE_LIMIT_MAX: process.env.AUTH_RATE_LIMIT_MAX || "10",
  CORS_ORIGINS: process.env.CORS_ORIGINS || "",
  BODY_LIMIT: process.env.BODY_LIMIT || "1mb",
  FAIL_CLOSED_ON_DETECTOR_ERROR: process.env.FAIL_CLOSED_ON_DETECTOR_ERROR || "false",
  GROQ_API_KEY: process.env.GROQ_API_KEY || "",
  GROQ_MODEL: process.env.GROQ_MODEL || "llama-3.1-8b-instant",
  GROQ_TIMEOUT_MS: process.env.GROQ_TIMEOUT_MS || "2500",
  GROQ_PAYLOAD_MAX_CHARS: process.env.GROQ_PAYLOAD_MAX_CHARS || "6000",
  FASTAPI_INTERNAL_TOKEN: process.env.FASTAPI_INTERNAL_TOKEN || "",
  SHADOW_MODE: process.env.SHADOW_MODE || "false",
  DEFAULT_BLOCK_THRESHOLD: process.env.DEFAULT_BLOCK_THRESHOLD || "0.75",
  DEFAULT_ALERT_THRESHOLD: process.env.DEFAULT_ALERT_THRESHOLD || "0.5",
  DEFAULT_OVERRIDE_THRESHOLD: process.env.DEFAULT_OVERRIDE_THRESHOLD || "0.9",
  DDOS_THRESHOLD_RPS: process.env.DDOS_THRESHOLD_RPS || "0.8",
  DDOS_GRACE_REQUESTS: process.env.DDOS_GRACE_REQUESTS || "8",
  DDOS_BLOCK_DURATION_MS: process.env.DDOS_BLOCK_DURATION_MS || "60000",
};
